using Microsoft.AspNetCore.Mvc;
using SwaggerMcp.Attributes;

[ApiController]
[Route("api/[controller]")]
public class OrdersController : ControllerBase
{
    List<Order> orders = new List<Order>(); // In-memory list to store orders for demonstration
    public OrdersController()
    {
        orders.Add(new Order
        {
            Id = 1,
            ProductName = "Sample Product",
            Quantity = 1,
            Price = 19.99m
        });

    }
    [HttpGet("{id}")]
    [McpTool("get_order", Description = "Retrieves a single order by ID")]
    public async Task<Order> GetOrder(int id) { 
    
        return orders.FirstOrDefault(o => o.Id == id) ?? new Order(); // In a real implementation, this would query the database
    }

    [HttpPost]
    [McpTool("create_order", Description = "Creates a new order")]
    public async Task<Order> CreateOrder(CreateOrderRequest body) {

        var order =  new Order()
        {
            Id = orders.Count, // In a real implementation, this would be generated by the database
            ProductName = body.ProductName,
            Quantity = body.Quantity,
            Price = body.Price
        };
        orders.Add(order); // In a real implementation, this would save to the database
        return order;
    }


    [HttpGet]                          // NOT tagged — invisible to MCP
    [McpTool("get_all_orders", Description = "Returns a list of all orders")]
    public async Task<List<Order>> GetAll() {
    return orders; // In a real implementation, this would query the database
    }
}